#!/usr/bin/env bash

# Check for the correct number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

# Function to display information about a subdomain
display_info() {
    local sub="$1"
    local record_type="$2"
    local destination="$3"
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

# Function to query DNS and display information
query_dns() {
    local sub="$1"
    query_result=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print}')
    record_type=$(echo "$query_result" | awk '{print $4}')
    destination=$(echo "$query_result" | awk '{print $5}')
    display_info "$sub" "$record_type" "$destination"
}

# Add subdomains and display information based on arguments provided
if [ -z "$subdomain" ]; then
    # Display information for default subdomains
    query_dns www 52.23.213.20
    query_dns lb-01 52.23.213.20
    query_dns web-01 100.25.118.17
    query_dns web-02 54.160.79.1
else
    # Display information for the specified subdomain
    query_dns "$subdomain"
fi

