#!/bin/bash

# Check if the correct number of parameters is provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Disable strict host key checking
scp_options="-o StrictHostKeyChecking=no"

# Transfer the file to the user's home directory on the server
scp $scp_options -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

# Check if the SCP command was successful
if [ $? -eq 0 ]; then
  echo "$file_path transferred successfully to $username@$server_ip:~/"
else
  echo "File transfer failed."
fi
