#!/usr/bin/env bash
# This script installs Nginx and configures it to return "Hello World!" on the root URL.

apt-get update
apt-get -y install nginx

echo -e "<html>\n<head>\n</head>\n<body>\nHello World!\n</body>\n</html>" > /var/www/html/index.html

sed -i '/listen \[::\]:80 default_server/a location / {\n    return 200 "Hello World!";\n}' /etc/nginx/sites-available/default

kill -HUP "$(cat /var/run/nginx.pid)"
