#!/usr/bin/env bash
# This script configures Nginx to perform a 301 Moved Permanently redirection for /redirect_me.

# Create a configuration file for the redirection
echo 'server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove the default Nginx configuration
rm -f /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart

