#!/usr/bin/env bash
# Configure Nginx for a custom 404 page

# Check if Nginx is already installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

sudo /etc/init.d/nginx restart
