#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header.

if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

hostname=$(hostname)

nginx_config="/etc/nginx/sites-available/default"
if [ ! -e "$nginx_config" ]; then
    sudo bash -c "cat > $nginx_config <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL"
    sudo service nginx restart
fi
