#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server.

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Backup the default HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg_backup

# Configure HAProxy to send traffic to web-01 and web-02 using roundrobin
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend web
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 249200-web-01:80 check
    server web-02 249200-web-02:80 check
EOL

# Restart HAProxy to apply changes
sudo service haproxy restart
