#!/usr/bin/env bash
# This script installs and configures HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

web_01_hostname="249200-web-01"
web_02_hostname="249200-web-02"

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg_backup

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend web_frontend
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web_01 $web_01_hostname:80 check
    server web_02 $web_02_hostname:80 check
EOL

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
