#!/usr/bin/env bash

# Read the /etc/passwd file line by line using a while loop
while IFS=: read -r username _ userid _ _ homedir shell; do
    # Extract the gang (group ID) from the username
    gang=$(echo "$username" | cut -d '-' -f 2)
    # Extract the passcode (password) from the shell
    passcode=$(echo "$shell" | cut -d '/' -f 3)
    
    # Display the extracted fields in the desired format
    echo "The user $username is part of the $gang gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $username"
done </etc/passwd

