#!/usr/bin/env bash
# Listen on port 98 on localhost

# Check if the script is run with root/sudo privileges
if [ "$(id -u)" -ne 0 ]; then
  echo "This script requires root privileges. Please run it with sudo."
  exit 1
fi

# Use netcat (nc) to listen on port 98
nc -l -p 98

